=== plevold/dm-core-packages/_schema/recipe.schema.json
{
  "type": "object",
  "description": "Schema for writing correct blueprints",
  "$defs": {
    "type": {
      "type": "string",
      "enum": ["CORE:RecipeLink", "dmss://system/SIMOS/RecipeLink"]
    },
    "uiRecipes": {
      "type": "string",
      "enum": ["CORE:UiRecipe", "dmss://system/SIMOS/UiRecipe"]
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalItems": false,
  "properties": {
    "type": {
      "$ref": "#/$defs/type"
    },
    "_blueprintPath_": {
      "type": "string"
    },
    "initialUiRecipe": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/$defs/uiRecipes"
        },
        "config": {
          "$ref": "recipeConfig.schema.json"
        },
        "plugin": {
          "type": "string"
        }
      },
      "required": ["type", "plugin", "config"]
    },
    "uiRecipes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "plugin": {
            "type": "string"
          }
        },
        "required": ["type", "plugin"]
      }
    }
  },
  "required": ["type", "_blueprintPath_"],
  "title": "Blueprint schema"
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/DemoPackage/recipe_links/attribute_selector_sidebar_blueprint.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "blueprints/AttributeSelectorSidebarBlueprint",
  "initialUiRecipe": {
    "name": "AttributeSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/attribute-selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "firstAttribute"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "secondAttribute",
            "eds_icon": "edit"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "thirdAttribute",
            "eds_icon": "apps"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "type": "CORE:UiRecipe",
      "name": "home",
      "plugin": "recipe-selector"
    },
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/apps/ExampleApplication/ExampleApplication.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/apps/ExampleApplication/ExampleApplication",
  "initialUiRecipe": {
    "name": "Header",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/header/HeaderPluginConfig",
      "hideAbout": false,
      "hideUserInfo": false,
      "uiRecipesList": ["Explorer", "Yaml"]
    },
    "plugin": "@development-framework/dm-core-plugins/header"
  },
  "uiRecipes": [
    {
      "name": "Explorer",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/explorer"
    },
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/orderItem.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/responsive_grid/example/blueprints/OrderItem",
  "initialUiRecipe": {
    "name": "UiRecipesSelector",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Edit",
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Edit",
              "type": "CORE:UiRecipe",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "self"
          }
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Form",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    },
    {
      "name": "List",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/list/ListPluginConfig",
        "functionality": {
          "type": "PLUGINS:dm-core-plugins/list/FunctionalityConfig",
          "delete": true,
          "expand": true
        },
        "headers": ["name", "quantity", "type"]
      },
      "dimensions": "*",
      "plugin": "@development-framework/dm-core-plugins/list"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/apps/MySignalApp/instances/CaseUISelector.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "AppModels:signals_simple/Case",
  "initialUiRecipe": {
    "name": "UiRecipesSelector",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Tabs",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Tabs",
            "scope": "self"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Run",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Run",
            "scope": "self"
          }
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "yaml-view"
    },
    {
      "name": "Tabs",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
        "childTabsOnRender": true
      },
      "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
    },
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "description": "Default edit",
      "plugin": "form"
    },
    {
      "name": "Run",
      "type": "CORE:UiRecipe",
      "description": "running",
      "plugin": "signal-job"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/appDefault.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "_default_",
  "initialUiRecipe": {
    "name": "Tabs",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true
    },
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
  },
  "uiRecipes": [
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/example/viewSelectorSidebar.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/example/blueprints/ViewSelectorSidebar",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Edit",
              "type": "CORE:UiRecipe",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "firstAttribute"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Edit",
              "type": "CORE:UiRecipe",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "secondAttribute",
            "eds_icon": "edit"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Edit",
              "type": "CORE:UiRecipe",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "thirdAttribute",
            "eds_icon": "apps"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/study.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "AppModels:signals_simple/Study",
  "initialUiRecipe": {
    "name": "Tabs",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/attribute-selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": false,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "label": "Home",
          "view": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Edit"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/grid/orderItem.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/grid/blueprints/OrderItem",
  "initialUiRecipe": {
    "name": "UiRecipesSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Edit",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "self"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Form",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    },
    {
      "name": "List",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/generic_list",
      "dimensions": "*",
      "config": {
        "type": "PLUGINS:dm-core-plugins/generic_list/GenericListPluginConfig",
        "headers": ["name", "quantity", "type"],
        "functionality": {
          "type": "PLUGINS:dm-core-plugins/generic_list/FunctionalityConfig",
          "delete": true
        }
      }
    }
  ]
}
