=== plevold/dm-core-packages/_schema/recipe.schema.json
{
  "type": "object",
  "description": "Schema for writing correct blueprints",
  "$defs": {
    "type": {
      "type": "string",
      "enum": ["CORE:RecipeLink", "dmss://system/SIMOS/RecipeLink"]
    },
    "uiRecipes": {
      "type": "string",
      "enum": ["CORE:UiRecipe", "dmss://system/SIMOS/UiRecipe"]
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalItems": false,
  "properties": {
    "type": {
      "$ref": "#/$defs/type"
    },
    "_blueprintPath_": {
      "type": "string"
    },
    "initialUiRecipe": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/$defs/uiRecipes"
        },
        "config": {
          "$ref": "recipeConfig.schema.json"
        },
        "plugin": {
          "type": "string"
        }
      },
      "required": ["type", "plugin", "config"]
    },
    "uiRecipes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "plugin": {
            "type": "string"
          }
        },
        "required": ["type", "plugin"]
      }
    }
  },
  "required": ["type", "_blueprintPath_"],
  "title": "Blueprint schema"
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/dummyBlueprint.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/blueprints/DummyBlueprint",
  "initialUiRecipe": {
    "name": "AttributeSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorItem",
          "label": "Edit self",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "self",
            "eds_icon": "edit"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorItem",
          "label": "Yaml view",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Yaml",
              "description": "Yaml view",
              "plugin": "@development-framework/dm-core-plugins/yaml"
            },
            "scope": "self"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorItem",
          "label": "Diagram",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Diagram",
              "description": "Default diagram",
              "plugin": "@development-framework/dm-core-plugins/blueprint-hierarchy"
            },
            "scope": "self"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorItem",
          "label": "List",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "List",
              "type": "CORE:UiRecipe",
              "plugin": "@development-framework/dm-core-plugins/generic-list",
              "dimensions": "*"
            },
            "scope": "self"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default blueprint edit",
      "plugin": "@development-framework/dm-core-plugins/blueprint"
    },
    {
      "name": "Diagram",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/blueprint-hierarchy"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/header/roles_header_example/person.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/header/roles_header_example/blueprints/Person",
  "initialUiRecipe": {
    "name": "RoleFilter",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/role_filter/RoleFilterConfig",
      "viewConfigs": [
        {
          "type": "CORE:ReferenceViewConfig",
          "recipe": "AdminHeader",
          "roles": ["dmss-admin", "developer"]
        },
        {
          "type": "CORE:ReferenceViewConfig",
          "recipe": "OperatorHeader",
          "roles": ["operator"]
        },
        {
          "type": "CORE:ReferenceViewConfig",
          "recipe": "Yaml"
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/role_filter"
  },
  "uiRecipes": [
    {
      "name": "AdminHeader",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/header/HeaderPluginConfig",
        "hideAbout": false,
        "hideUserInfo": true,
        "uiRecipesList": ["Yaml", "Edit", "Explorer"]
      },
      "plugin": "@development-framework/dm-core-plugins/header"
    },
    {
      "name": "OperatorHeader",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/header/HeaderPluginConfig",
        "hideAbout": false,
        "hideUserInfo": true,
        "uiRecipesList": ["Yaml", "Explorer"]
      },
      "plugin": "@development-framework/dm-core-plugins/header"
    },
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    },
    {
      "name": "Explorer",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/explorer"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/roles_school_example/schoolDistrict.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/roles_school_example/blueprints/SchoolDistrict",
  "initialUiRecipe": {
    "name": "RoleFilter",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/role_filter",
    "config": {
      "type": "PLUGINS:dm-core-plugins/role_filter/RoleFilterConfig",
      "viewConfigs": [
        {
          "type": "CORE:ReferenceViewConfig",
          "recipe": "AdminViewSelector",
          "roles": [
            "dmss-admin",
            "developer"
          ]
        },
        {
          "type": "CORE:ReferenceViewConfig",
          "recipe": "OperatorViewSelector",
          "roles": [
            "operator"
          ]
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "AdminViewSelector",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/view_selector",
      "config": {
        "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
        "childTabsOnRender": true,
        "asSidebar": true,
        "items": [
          {
            "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
            "label": "Hogwarts Admin",
            "viewConfig": {
              "type": "CORE:ReferenceViewConfig",
              "scope": "school",
              "eds_icon": "home",
              "recipe": "AdminView"
            }
          },
          {
            "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
            "label": "Hogwarts All",
            "viewConfig": {
              "type": "CORE:ReferenceViewConfig",
              "scope": "school",
              "eds_icon": "home",
              "recipe": "OperatorView"
            }
          }
        ]
      }
    },
    {
      "name": "OperatorViewSelector",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/view_selector",
      "config": {
        "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
        "childTabsOnRender": true,
        "asSidebar": true,
        "items": [
          {
            "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
            "label": "Hogwarts All",
            "viewConfig": {
              "type": "CORE:ReferenceViewConfig",
              "scope": "school",
              "eds_icon": "home",
              "recipe": "OperatorView"
            }
          }
        ]
      }
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/form/nestedExample.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/form/example/blueprints/NestedExample",
  "initialUiRecipe": {
    "name": "AttributeSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": false,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/AttributeSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "self"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "custom",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml",
      "category": "view"
    },
    {
      "name": "Form",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form",
      "category": "edit"
    },
    {
      "name": "aRecipeName",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form",
      "category": "edit",
      "config": {
        "type": "PLUGINS:dm-core-plugins/form/FormInput",
        "attributes": [
          {
            "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
            "name": "bar",
            "widget": "TextareaWidget"
          }
        ]
      }
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/apps/EmployeeApp/employee.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/apps/EmployeeApp/blueprints/Employee",
  "initialUiRecipe": {
    "name": "Edit",
    "type": "CORE:UiRecipe",
    "description": "Default edit",
    "config": {
      "type": "PLUGINS:dm-core-plugins/form/FormInput",
      "attributes": [
        {
          "name": "description",
          "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
          "widget": "TextareaWidget"
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/form"
  },
  "uiRecipes": [
    {
      "name": "List",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/list/ListPluginConfig",
        "functionality": {
          "type": "PLUGINS:dm-core-plugins/list/FunctionalityConfig",
          "delete": true,
          "expand": true,
          "open": true
        },
        "headers": ["name", "description"],
        "label": "Employee number",
        "labelByIndex": true
      },
      "dimensions": "*",
      "plugin": "@development-framework/dm-core-plugins/list"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/grid/example/dashboard.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/grid/example/blueprints/Dashboard",
  "initialUiRecipe": {
    "name": "Dashboard",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/grid/GridPluginConfig",
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "columnEnd": 6,
            "columnStart": 1,
            "rowEnd": 1,
            "rowStart": 1
          },
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "aRecipeName",
            "scope": "aNestedObjectWithCustomUI"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "columnEnd": 6,
            "columnStart": 4,
            "rowEnd": 2,
            "rowStart": 2
          },
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "form",
              "type": "CORE:UiRecipe",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "attributes": [
                  {
                    "name": "bar",
                    "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
                    "widget": "TextareaWidget"
                  }
                ]
              },
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "aNestedObjectWithCustomUI"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "columnEnd": 3,
            "columnStart": 1,
            "rowEnd": 4,
            "rowStart": 4
          },
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Yaml",
            "scope": "orders[0].product"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "columnEnd": 6,
            "columnStart": 4,
            "rowEnd": 4,
            "rowStart": 4
          },
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Form",
            "scope": "order.product"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "columnEnd": 6,
            "columnStart": 1,
            "rowEnd": 5,
            "rowStart": 5
          },
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Json",
              "type": "CORE:UiRecipe",
              "plugin": "@development-framework/dm-core-plugins/json"
            }
          }
        }
      ],
      "size": {
        "type": "PLUGINS:dm-core-plugins/grid/GridSize",
        "columns": 6,
        "rows": 5
      }
    },
    "plugin": "@development-framework/dm-core-plugins/grid"
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/form/enums/enums.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/form/enums/blueprints/Enums",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Enums",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Enums"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Yaml",
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Yaml",
              "type": "CORE:UiRecipe",
              "description": "Yaml view",
              "plugin": "@development-framework/dm-core-plugins/yaml",
              "showRefreshButton": true
            },
            "scope": "self"
          }
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
  },
  "uiRecipes": [
    {
      "name": "Enums",
      "type": "CORE:UiRecipe",
      "config": {
        "type": "PLUGINS:dm-core-plugins/form/FormInput",
        "attributes": [
          {
            "name": "singleString",
            "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
            "config": {
              "type": "PLUGINS:dm-core-plugins/form/widgets/SelectWidgetConfig",
              "multiline": false
            },
            "widget": "SelectWidget"
          },
          {
            "name": "manyStrings",
            "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
            "config": {
              "type": "PLUGINS:dm-core-plugins/form/widgets/SelectWidgetConfig",
              "multiline": true
            },
            "widget": "SelectWidget"
          }
        ]
      },
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/form/read_only/person.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/form/read_only/blueprints/Person",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "name": "Edit",
              "type": "CORE:UiRecipe",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form"
            },
            "scope": "self"
          }
        }
      ]
    },
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs"
  },
  "uiRecipes": [
    {
      "name": "defaultYaml",
      "type": "CORE:UiRecipe",
      "category": "view",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "defaultForm",
      "type": "CORE:UiRecipe",
      "category": "edit",
      "config": {
        "type": "PLUGINS:dm-core-plugins/form/FormInput",
        "readOnly": true
      },
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}
