=== plevold/dm-core-packages/_schema/recipe.schema.json
{
  "type": "object",
  "description": "Schema for writing correct blueprints",
  "$defs": {
    "type": {
      "type": "string",
      "enum": ["CORE:RecipeLink", "dmss://system/SIMOS/RecipeLink"]
    },
    "uiRecipes": {
      "type": "string",
      "enum": ["CORE:UiRecipe", "dmss://system/SIMOS/UiRecipe"]
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalItems": false,
  "properties": {
    "type": {
      "$ref": "#/$defs/type"
    },
    "_blueprintPath_": {
      "type": "string"
    },
    "initialUiRecipe": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "$ref": "#/$defs/uiRecipes"
        },
        "config": {
          "$ref": "recipeConfig.schema.json"
        },
        "plugin": {
          "type": "string"
        }
      },
      "required": ["type", "plugin", "config"]
    },
    "uiRecipes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "plugin": {
            "type": "string"
          }
        },
        "required": ["type", "plugin"]
      }
    }
  },
  "required": ["type", "_blueprintPath_"],
  "title": "Blueprint schema"
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/nested.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/grid/example/blueprints/Nested",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "config": {},
    "plugin": "@development-framework/dm-core-plugins/view_selector"
  },
  "uiRecipes": [
    {
      "name": "custom",
      "type": "CORE:UiRecipe",
      "category": "view",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Form",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/carGarage.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/car_garage/blueprints/CarGarage",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": true,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Garage",
              "description": "",
              "plugin": "@development-framework/dm-core-plugins/form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "fields": ["name", "description"]
              }
            },
            "scope": "self",
            "eds_icon": "home"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:ReferenceViewConfig",
            "scope": "Audi",
            "eds_icon": "car"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "view": {
            "type": "CORE:ReferenceViewConfig",
            "scope": "Volvo",
            "eds_icon": "car"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/DemoPackage/recipe_links/tabs_as_sidebar_blueprint.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "blueprints/TabsAsSidebarBlueprint",
  "initialUiRecipe": {
    "name": "AttributeSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/attribute-selector",
    "config": {
      "type": "blueprints/Plugins/AttributeSelectorPluginConfig",
      "childTabsOnRender": true,
      "asSidebar": true,
      "homeRecipe": "home"
    }
  },
  "uiRecipes": [
    {
      "type": "CORE:UiRecipe",
      "name": "home",
      "plugin": "UiPluginSelector",
      "config": {
        "type": "blueprints/Plugins/UiPluginSelectorConfig",
        "recipes": ["Yaml", "Edit"]
      }
    },
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "yaml",
      "category": "container"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/list/order_example/blueprints/Order",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector/tabs",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true
    }
  },
  "uiRecipes": [
    {
      "name": "Form",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    },
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "List",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/list",
      "dimensions": "*",
      "config": {
        "type": "PLUGINS:dm-core-plugins/list/ListPluginConfig",
        "viewConfigs": [],
        "headers": [
          "name",
          "description"
        ],
        "openAsTab": true,
        "functionality": {
          "type": "PLUGINS:dm-core-plugins/list/FunctionalityConfig",
          "delete": true
        }
      }
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/DemoPackage/recipe_links/blueprint.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "CORE:Blueprint",
  "initialUiRecipe": {
    "name": "UiPluginSelector",
    "type": "CORE:UiRecipe",
    "plugin": "UiPluginSelector",
    "config": {}
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default blueprint edit",
      "plugin": "@development-framework/dm-core-plugins/blueprint"
    },
    {
      "name": "Diagram",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/blueprint-hierarchy"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/technical.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/car_garage/blueprints/TechBlueprint",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": false,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "EU control",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "fields": ["controlDate", "nextControl"]
              }
            },
            "eds_icon": "check"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Dimensions",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "fields": ["width", "length", "heigth"]
              }
            },
            "eds_icon": "car"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml",
      "category": "container"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/containers/EquallySpacedSignalUI.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "AppModels:containers/EquallySpacedSignal",
  "initialUiRecipe": {
    "name": "UiRecipesSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/attribute-selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorConfig",
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "label": "Plot",
          "view": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Plot",
            "scope": "self"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/attribute-selector/AttributeSelectorItem",
          "label": "Table",
          "view": {
            "type": "CORE:ReferenceViewConfig",
            "recipe": "Table",
            "scope": "self"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Plot",
      "type": "CORE:UiRecipe",
      "plugin": "marmo-ess-plot-view"
    },
    {
      "name": "Table",
      "type": "CORE:UiRecipe",
      "plugin": "marmo-ess-table-view"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

=== plevold/dm-core-packages/example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/owner.recipe.json
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/view_selector/car_garage/blueprints/OwnerBlueprint",
  "initialUiRecipe": {
    "name": "ViewSelector",
    "type": "CORE:UiRecipe",
    "plugin": "@development-framework/dm-core-plugins/view_selector",
    "config": {
      "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorConfig",
      "childTabsOnRender": true,
      "asSidebar": false,
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Owner details",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "fields": ["name", "DateOwned"]
              }
            },
            "eds_icon": "person"
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/view_selector/ViewSelectorItem",
          "label": "Owner history",
          "view": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "name": "Edit",
              "description": "Default edit",
              "plugin": "@development-framework/dm-core-plugins/form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "fields": ["earlierOwners"]
              }
            },
            "eds_icon": "group"
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml",
      "category": "container"
    },
    {
      "type": "CORE:UiRecipe",
      "name": "Edit",
      "description": "Default edit",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}
